---
version: '3.6'


networks:
    gitea:
    net:
        driver: bridge


services:
    freeipa:
        image: freeipa/freeipa-server:centos-8
        restart: unless-stopped
        hostname: freeipa.${MY_DOMAIN}
        networks:
            - net
        environment:
            - IPA_SERVER_HOSTNAME=freeipa.${MY_DOMAIN}
        tty: true
        stdin_open: true
        cap_add:
            - NET_ADMIN
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - ./freeipa:/data
        sysctls:
            - net.ipv6.conf.lo.disable_ipv6=0
            - net.ipv6.conf.all.disable_ipv6=0
        security_opt:
            - "seccomp:unconfined"
        command:
            - -U
            - --domain=${MY_DOMAIN}
            - --realm=${MY_DOMAIN}
            - --http-pin=${LDAP_PASS}
            - --dirsrv-pin=${LDAP_PASS}
            - --ds-password=${LDAP_PASS}
            - --admin-password=${LDAP_PASS}
            - --no-host-dns
            #- --no-dnssec-validation
            #- --setup-dns
            #- --auto-forwarders
            #- --allow-zone-overlap
            - --unattended
        expose:
            # 4.3.6 https://docs.fedoraproject.org/en-US/Fedora/17/html/FreeIPA_Guide/using-the-ui.html
            - 80
            - 443
        ports:
            #- "4444:443"
            #- "53:53/udp"
            #- "53:53"
            #- "80:80"
            #- "443:443"
            - "389:389"
            - "636:636"
            - "88:88"
            - "464:464"
            - "88:88/udp"
            - "464:464/udp"
            #- "123:123/udp"
            - "7389:7389"
            - "9443:9443"
            - "9444:9444"
            - "9445:9445"
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.public.rule=Host(`freeipa.${MY_DOMAIN}`)'
            - 'traefik.http.routers.public.entrypoints=https'
            - 'traefik.http.routers.public.tls=true'
            - 'traefik.http.routers.public.tls.options=default'
            - 'traefik.http.routers.public.middlewares=authelia@docker'



    authelia:
        image: authelia/authelia
        container_name: authelia
        #env_file: .env
        volumes:
            - ./authelia:/config
        networks:
            - net
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.authelia.rule=Host(`authelia.${MY_DOMAIN}`)'
            - 'traefik.http.routers.authelia.entrypoints=https'
            - 'traefik.http.routers.authelia.tls=true'
            - 'traefik.http.routers.authelia.tls.options=default'
            - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.${MY_DOMAIN}'  # yamllint disable-line rule:line-length
            - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
            - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
        expose:
            - 9091
        restart: unless-stopped
        healthcheck:
            disable: true
        environment:
        - TZ=Australia/Melbourne

    traefik:
        image: traefik:2.4
        container_name: traefik
        #env_file: ../.env
        volumes:
            - ./traefik:/etc/traefik
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - net
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.api.rule=Host(`traefik.${MY_DOMAIN}`)'
            - 'traefik.http.routers.api.entrypoints=https'
            - 'traefik.http.routers.api.service=api@internal'
            - 'traefik.http.routers.api.tls=true'
            - 'traefik.http.routers.api.tls.options=default'
            - 'traefik.http.routers.api.middlewares=authelia@docker'
        ports:
            - 80:80
            - 443:443
        command:
            - '--api'
            - '--providers.docker=true'
            - '--providers.docker.exposedByDefault=false'
            - '--providers.file.filename=/etc/traefik/certificates.yml'
            - '--entrypoints.http=true'
            - '--entrypoints.http.address=:80'
            - '--entrypoints.http.http.redirections.entrypoint.to=https'
            - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
            - '--entrypoints.https=true'
            - '--entrypoints.https.address=:443'
            - '--log=true'
            - '--log.level=DEBUG'

    secure:
        image: traefik/whoami
        container_name: secure
        #env_file: ../.env
        networks:
            - net
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.secure.rule=Host(`secure.${MY_DOMAIN}`)'
            - 'traefik.http.routers.secure.entrypoints=https'
            - 'traefik.http.routers.secure.tls=true'
            - 'traefik.http.routers.secure.tls.options=default'
            - 'traefik.http.routers.secure.middlewares=authelia@docker'
        expose:
            - 80
        restart: unless-stopped

    public:
        image: traefik/whoami
        container_name: public
        #env_file: ../.env
        networks:
            - net
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.public.rule=Host(`public.${MY_DOMAIN}`)'
            - 'traefik.http.routers.public.entrypoints=https'
            - 'traefik.http.routers.public.tls=true'
            - 'traefik.http.routers.public.tls.options=default'
            - 'traefik.http.routers.public.middlewares=authelia@docker'
        expose:
            - 80
        restart: unless-stopped
