version: '3.3'

networks:
    traefik-homelab:
      external:
        name: traefik-homelab
volumes:
    jellyfin-config:
      external: true
    jellyfin-media:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NFS_MEDIA},nolock,soft,rw
        device: ":${NFS_MEDIA_LOCATION}"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    #user: "0:0"
    environment:
      - PUID=1001
      - PGID=1002
      - TZ=America/New_York
      #- UMASK_SET=<022> #optional
    volumes:
       - jellyfin-config:/config
       - jellyfin-media:/media
      #- /opt/vc/lib:/opt/vc/lib #optional
    expose:
      - 8096
    #ports:
    #  - 8096:8096
    #  - 8920:8920 #optional
    #  - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
      #- /dev/vcsm:/dev/vcsm #optional
      #- /dev/vchiq:/dev/vchiq #optional
      #- /dev/video10:/dev/video10 #optional
      #- /dev/video11:/dev/video11 #optional
      #- /dev/video12:/dev/video12 #optional
    restart: unless-stopped
    networks:
        - traefik-homelab
    labels:
        - "traefik.enable=true"
        - 'traefik.http.routers.jellyfin.entrypoints=https'
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${MY_DOMAIN}`)"
        - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
        - "traefik.http.routers.jellyfin.service=jellyfin@docker"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
        - "traefik.http.routers.jellyfin.middlewares=authelia@docker"
        - "traefik.http.routers.jellyfin.tls.options=default"
        - "traefik.docker.network=traefik-homelab"
