version: "3"
  
networks:
    traefik-homelab:
      external:
        name: traefik-homelab

services:
    filebrowser:
        image: filebrowser/filebrowser
        container_name: filebrowser
        user: root
        restart: unless-stopped
        volumes:
            - ${VOLUME_DIR}:/srv
            #- ./filebrowser/filebrowser.db:/database.db
            #- ./filebrowser/filebrowser.json:/.filebrowser.json
        networks:
            - traefik-homelab
        expose:
            - "80"
        labels:
            - "traefik.enable=true"
            - 'traefik.http.routers.filebrowser.entrypoints=https'
            - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.${MY_DOMAIN}`)"
            - "traefik.http.routers.filebrowser.tls.certresolver=myresolver"
            - "traefik.http.routers.filebrowser.service=filebrowser@docker"
            - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
            - "traefik.http.routers.filebrowser.middlewares=authelia@docker"
            - "traefik.http.routers.filebrowser.tls.options=default"
            - "traefik.docker.network=traefik-homelab"
            
