version: '3'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:1.1.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - mah_path/opensearch-config/internal_user.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - opensearch-data1:/usr/share/opensearch/data
      #- ./opensearch-config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
      - traefik-homelab
    labels:
        - "traefik.enable=true"
        - 'traefik.http.routers.opensearch-node1.entrypoints=https'
        - "traefik.http.routers.opensearch-node1.rule=Host(`opensearch.${MY_DOMAIN}`)"
        - "traefik.http.routers.opensearch-node1.tls.certresolver=myresolver"
        - "traefik.http.routers.opensearch-node1.service=opensearch-node1@docker"
        - "traefik.http.services.opensearch-node1.loadbalancer.server.port=9200"
        - "traefik.http.routers.opensearch-node1.tls.options=default"
        - "traefik.docker.network=traefik-homelab"
  opensearch-node2:
    image: opensearchproject/opensearch:1.1.0
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - mah_path/opensearch-config/internal_user.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      - opensearch-data2:/usr/share/opensearch/data
      #- ./opensearch-config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.1.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' # must be a string with no spaces when specified as an environment variable
    networks:
      - opensearch-net
      - traefik-homelab
    labels:
        - "traefik.enable=true"
        - 'traefik.http.routers.opensearch-dashboards.entrypoints=https'
        - "traefik.http.routers.opensearch-dashboards.rule=Host(`kibana.${MY_DOMAIN}`)"
        - "traefik.http.routers.opensearch-dashboards.tls.certresolver=myresolver"
        - "traefik.http.routers.opensearch-dashboards.service=opensearch-dashboards@docker"
        - "traefik.http.services.opensearch-dashboards.loadbalancer.server.port=5601"
        - "traefik.http.routers.opensearch-dashboards.tls.options=default"
        - "traefik.docker.network=traefik-homelab"

volumes:
  opensearch-data1:
    external:
      name: opensearch-data1
  opensearch-data2:
    external:
      name: opensearch-data1

networks:
  opensearch-net:
  traefik-homelab:
    external:
      name: traefik-homelab
