version: '3.3'

networks:
    traefik-homelab:
      external:
        name: traefik-homelab

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      #- UMASK_SET=<022> #optional
    volumes:
       - ${VOLUME_DIR}/jellyfin:/config
      #- /opt/vc/lib:/opt/vc/lib #optional
    expose:
      - 8096
    #ports:
    #  - 8096:8096
    #  - 8920:8920 #optional
    #  - 7359:7359/udp #optional
    #  - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
      #- /dev/vcsm:/dev/vcsm #optional
      #- /dev/vchiq:/dev/vchiq #optional
      #- /dev/video10:/dev/video10 #optional
      #- /dev/video11:/dev/video11 #optional
      #- /dev/video12:/dev/video12 #optional
    restart: unless-stopped
    networks:
        - traefik-homelab
    labels:
        - "traefik.enable=true"
        - 'traefik.http.routers.jellyfin.entrypoints=https'
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${MY_DOMAIN}`)"
        - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
        - "traefik.http.routers.jellyfin.service=jellyfin@docker"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
        - "traefik.http.routers.jellyfin.middlewares=authelia@docker"
        - "traefik.http.routers.jellyfin.tls.options=default"
        - "traefik.docker.network=traefik-homelab"
