version: '3'
services:
    whoami:
        image: "traefik/whoami"
        container_name: "simple-service"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`whoami.com`)"
            - "traefik.http.routers.whoami.entrypoints=web"
        networks:
            - traefik-homelab
networks:
    traefik-homelab:
        external:
            name: traefik-homelab
