version: "3.4"

services:
  app:
    image: monica
    container_name: monica
    depends_on:
      - monica-db
    #ports:
    #  - 8080:80
    expose:
        - "80"
    networks:
        - traefik-homelab
        - monica-network
    environment:
      - "APP_KEY=base64:OY3HtmTu8LrdBlOvNrBpb57C8rjkEggWntn5BFh9jDg=" # echo -n 'base64:'; openssl rand -base64 32
      - APP_ENV=local
      - APP_TRUSTED_PROXIES=*
      - DB_HOST=monica-db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=secret
    volumes:
      - data:/var/www/html/storage
    restart: always
    labels:
        - "traefik.enable=true"
        - 'traefik.http.routers.monica.entrypoints=https'
        - "traefik.http.routers.monica.rule=Host(`monica.${MY_DOMAIN}`)"
        - "traefik.http.routers.monica.tls.certresolver=myresolver"
        - "traefik.http.routers.monica.service=monica@docker"
        - "traefik.http.services.monica.loadbalancer.server.port=80"
        - "traefik.http.routers.monica.middlewares=authelia@docker"
        - "traefik.http.routers.monica.tls.options=default"
        - "traefik.docker.network=traefik-homelab"

  monica-db:
    image: mysql:5.7
    container_name: monica-db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=usermonica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - monica-network
    expose:
      - "3306"
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql

networks:
  traefik-homelab:
    external:
      name: traefik-homelab
  monica-network:
    internal: true
      